### ISSUE TITLE
NameError (undefined local variable or method `params' for Noticed::DeliveryMethods::Slack)

### ISSUE THREAD

**Issue by itsderek23** [excid3/noticed#12]
Nice gem!

I'm starting off with a trivial (perhaps too trivial) test of noticed by attempting to send a notification via Slack. However, I'm getting an exception like the following:

```
NameError (undefined local variable or method `params' for #<Noticed::DeliveryMethods::Slack:0x00007fe84c209270>)
```

My bare-bones notification class:

```ruby
class CommentNotification < Noticed::Base
  deliver_by :database
  deliver_by :slack

  param :text
end
```

And output from Rails console:

```ruby
2.6.4 :008 > notification = CommentNotification.with(text: "this is the comment text")
 => #<CommentNotification:0x00007fe84c351420 @params={:text=>"this is the comment text"}> 
2.6.4 :009 > notification.deliver(User.all)
  User Load (0.2ms)  SELECT "users".* FROM "users"
Performing Noticed::DeliveryMethods::Database (Job ID: 9dfa7ae6-3273-4bb6-b0cf-fb15a0c0bb4c) from Async(default) enqueued at  with arguments: {:notification_class=>"CommentNotification", :options=>{}, :params=>{:text=>"this is the comment text"}, :recipient=>#<GlobalID:0x00007fe84c368fd0 @uri=#<URI::GID gid://rails-noticed/User/1>>, :record=>nil}
   (0.1ms)  begin transaction
  Notification Create (0.4ms)  INSERT INTO "notifications" ("recipient_type", "recipient_id", "type", "params", "created_at", "updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["recipient_type", "User"], ["recipient_id", 1], ["type", "CommentNotification"], ["params", "{\"text\":\"this is the comment text\",\"_aj_symbol_keys\":[\"text\"]}"], ["created_at", "2020-08-06 18:50:33.269880"], ["updated_at", "2020-08-06 18:50:33.269880"]]
   (1.5ms)  commit transaction
Performed Noticed::DeliveryMethods::Database (Job ID: 9dfa7ae6-3273-4bb6-b0cf-fb15a0c0bb4c) from Async(default) in 4.37ms
Performing Noticed::DeliveryMethods::Slack (Job ID: 5e06cff1-5057-4ea7-bcdb-f7c0c1f637ef) from Async(default) enqueued at  with arguments: {:notification_class=>"CommentNotification", :options=>{}, :params=>{:text=>"this is the comment text"}, :recipient=>#<GlobalID:0x00007fe848649e10 @uri=#<URI::GID gid://rails-noticed/User/1>>, :record=>#<GlobalID:0x00007fe8486491e0 @uri=#<URI::GID gid://rails-noticed/Notification/6>>}
Error performing Noticed::DeliveryMethods::Slack (Job ID: 5e06cff1-5057-4ea7-bcdb-f7c0c1f637ef) from Async(default) in 3.33ms: NameError (undefined local variable or method `params' for #<Noticed::DeliveryMethods::Slack:0x00007fe84864bc88>):
/Users/dlite/.rvm/gems/ruby-2.6.4/gems/noticed-1.2.5/lib/noticed/delivery_methods/slack.rb:14:in `format'
/Users/dlite/.rvm/gems/ruby-2.6.4/gems/noticed-1.2.5/lib/noticed/delivery_methods/slack.rb:5:in `deliver'
/Users/dlite/.rvm/gems/ruby-2.6.4/gems/noticed-1.2.5/lib/noticed/delivery_methods/base.rb:20:in `block in perform'
/Users/dlite/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
```

Perhaps the `params` method / variable [referenced here](https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/slack.rb#L14) does not exist in a parent class? Or my trivial example is missing something obvious?

**Comment by excid3** [comment]
I haven't thoroughly tested Slack, Twilio, and Vonage like the others. I think it's just a typo there.

https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/slack.rb#L14 should probably be `notification.params`

**Comment by itsderek23** [comment]
Yep - that was it. Thanks!

See #13 for a fix.
