### ISSUE TITLE
Migration Failure

### ISSUE THREAD

**Issue by chibuezeayogu** [excid3/noticed#155]
Gemfile: 
- gem 'mysql2', '~> 0.5'

Docker compose file:
```
- version: '3'
  services:
      mysql:
        image: mysql:5.6.47
        restart: always
     ports:
        - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
```

After running the command
`rails generate noticed:model`

I ran 
`rails db:migrate`

and I got this error 
```
Creating staffomatic_user_management_api_run ... done
== 20210927053645 CreateNotifications: migrating ==============================
-- create_table(:notifications)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json, `read_at` datetime, `created_at` datetime(6) NOT NULL, `updated_at` dateti' at line 1
/app/db/migrate/20210927053645_create_notifications.rb:3:in `change'
/app/bin/rails:5:in `<top (required)>'
/app/bin/spring:10:in `require'
/app/bin/spring:10:in `block in <top (required)>'
/app/bin/spring:7:in `tap'
/app/bin/spring:7:in `<top (required)>'

Caused by:
ActiveRecord::StatementInvalid: Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json, `read_at` datetime, `created_at` datetime(6) NOT NULL, `updated_at` dateti' at line 1
/app/db/migrate/20210927053645_create_notifications.rb:3:in `change'
/app/bin/rails:5:in `<top (required)>'
/app/bin/spring:10:in `require'
/app/bin/spring:10:in `block in <top (required)>'
/app/bin/spring:7:in `tap'
/app/bin/spring:7:in `<top (required)>'

Caused by:
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json, `read_at` datetime, `created_at` datetime(6) NOT NULL, `updated_at` dateti' at line 1
/app/db/migrate/20210927053645_create_notifications.rb:3:in `change'
/app/bin/rails:5:in `<top (required)>'
/app/bin/spring:10:in `require'
/app/bin/spring:10:in `block in <top (required)>'
/app/bin/spring:7:in `tap'
/app/bin/spring:7:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)```

Any ideas will be much appreciated.

**Comment by excid3** [comment]
You'll want to update your MySQL version. 

MySQL 5.7.8 introduces the JSON type. Considering MySQL is on version 8, you're very far behind.

**Comment by chibuezeayogu** [comment]
@excid3 thanks
