### ISSUE TITLE
Custom delivery method docs might be incorrect

### ISSUE THREAD

**Issue by dwightwatson** [excid3/noticed#227]
I'm working on an Expo push notifications delivery method (happy to PR it if you'd consider it) but running into an issue using one of the syntaxes [provided in the docs under `Limitations`](https://github.com/excid3/noticed#limitations).

```rb
deliver_by DeliveryMethods::Expo
```

When I try and use this in my app I simply get an error:

```
An error occurred while loading ./spec/notifications/new_signature_notification_spec.rb.
Failure/Error: deliver_by DeliveryMethods::Expo

NoMethodError:
  undefined method `to_sym' for DeliveryMethods::Expo:Class

              name = name.to_sym
                         ^^^^^^^
  Did you mean?  to_s
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:921:in `block in define_callbacks'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:920:in `each'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activesupport-7.0.3/lib/active_support/callbacks.rb:920:in `define_callbacks'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activemodel-7.0.3/lib/active_model/callbacks.rb:120:in `block in define_model_callbacks'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activemodel-7.0.3/lib/active_model/callbacks.rb:119:in `each'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/activemodel-7.0.3/lib/active_model/callbacks.rb:119:in `define_model_callbacks'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:20:in `deliver_by'
# ./app/notifications/new_signature_notification.rb:8:in `<class:NewSignatureNotification>'
# ./app/notifications/new_signature_notification.rb:1:in `<main>'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:27:in `require'
# ./spec/notifications/new_signature_notification_spec.rb:3:in `<main>'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2115:in `load_file_handling_errors'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1615:in `block in load_spec_files'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1613:in `each'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:1613:in `load_spec_files'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:102:in `setup'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:86:in `run'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/rspec:25:in `load'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bin/rspec:25:in `<top (required)>'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `load'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:58:in `kernel_load'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli/exec.rb:23:in `run'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:484:in `exec'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:31:in `dispatch'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/cli.rb:25:in `start'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/exe/bundle:48:in `block in <top (required)>'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
# /Users/dwight/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.8/exe/bundle:36:in `<top (required)>'
# /Users/dwight/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
# /Users/dwight/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
```

**Comment by cjilbert504** [comment]
@dwightwatson - Thanks for submitting this issue. I looked into this and for now, you can probably fix this in your app by wrapping the delivery method name you're sending to `deliver_by` in quotes, for example:
`deliver_by "DeliveryMethods::Expo"`

I'm going to look into this further, update documentation and hopefully provide a fix. 

Thanks again!

**Comment by excid3** [comment]
I think that we had changed some things since that was added to the readme. I'm with @cjilbert504 on this one. 

It will work better if we require you to provide a name like `:expo` and `class:` option so that callbacks and other things can be registered in a more predictable manner.

We will update the docs so that this is the recommended way:

```ruby
deliver_by :expo, class: "DeliveryMethods::Expo"
```
