### ISSUE TITLE
Calling a mailer method with the same name as an instance method raises an error

### ISSUE THREAD

**Issue by DRBragg** [excid3/noticed#236]
For additional details and context see this discussion: https://github.com/joemasilotti/railsdevs.com/pull/510#discussion_r903754249

## Description

Given a mailer that looks something like:
```ruby
class InvisiblizeMailer < ApplicationMailer
  def business
    @notification = params[:record].to_notification
    recipient = params[:recipient]

    @business = @notification.business

    mail(to: recipient.email)
  end
end
```
and a notification setup like:
```ruby
module Businesses
  class InvisiblizeNotification < ApplicationNotification
    deliver_by :database
    deliver_by :email, mailer: "InvisiblizeMailer", method: :business

    param :business

    def business
      params[:business]
    end
  end
end
```
I would expect the following to create a notification and send an email:
```ruby
business = Business.last
Businesses::InvisiblizeNotification.with(business: business).deliver_later(business.user)
```
Instead an exception is raised:
```
Error performing Noticed::DeliveryMethods::Email (Job ID: 38e2f818-336d-4e92-8089-ad487f5c24e7) from Sidekiq(default) in 25.47ms:
NoMethodError (undefined method `to_sym' for #<Business ...>
Did you mean?  to_s):
```
(Full stack trace is below)

### Versions

Ruby: 3.1.2
Rails: 7.0.2.4
Noticed: 1.5.9

<details closed>
  <summary>Full Details</summary>
```
Performing Noticed::DeliveryMethods::Database (Job ID: 7d220ddc-8346-4471-a559-c90e3b69573a) from Sidekiq(default) enqueued at  with arguments: {:notification_class=>"Businesses::InvisiblizeNotification", :options=>{}, :params=>{:business=>#<GlobalID:0x00000001098c7328 @uri=#<URI::GID gid://railsdevs/Business/2>>}, :recipient=>#<GlobalID:0x00000001098c6c98 @uri=#<URI::GID gid://railsdevs/User/26>>, :record=>nil}
Performed Noticed::DeliveryMethods::Database (Job ID: 7d220ddc-8346-4471-a559-c90e3b69573a) from Sidekiq(default) in 23.26ms
Performing Noticed::DeliveryMethods::Email (Job ID: 38e2f818-336d-4e92-8089-ad487f5c24e7) from Sidekiq(default) enqueued at  with arguments: {:notification_class=>"Businesses::InvisiblizeNotification", :options=>{:mailer=>"InvisiblizeMailer", :method=>:business}, :params=>{:business=>#<GlobalID:0x000000010997cfc0 @uri=#<URI::GID gid://railsdevs/Business/2>>}, :recipient=>#<GlobalID:0x000000010997ca48 @uri=#<URI::GID gid://railsdevs/User/26>>, :record=>#<GlobalID:0x000000010997c480 @uri=#<URI::GID gid://railsdevs/Notification/26>>}
Error performing Noticed::DeliveryMethods::Email (Job ID: 38e2f818-336d-4e92-8089-ad487f5c24e7) from Sidekiq(default) in 25.47ms: NoMethodError (undefined method `to_sym' for #<Business id: 2, user_id: 26, contact_name: "Norman Mills", company: "Roob-Cartwright", created_at: "2022-04-08 21:55:36.854830000 +0000", updated_at: "2022-06-26 16:32:26.504735000 +0000", bio: "Consequuntur dolor provident. Dicta repellat odio....", developer_notifications: "no", website: "helloworld.com", contact_role: "", invisible: true>
Did you mean?  to_s):
/Users/.../ruby/gems/3.1.0/gems/activemodel-7.0.2.4/lib/active_model/attribute_methods.rb:458:in `method_missing'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/delivery_methods/email.rb:10:in `deliver'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/delivery_methods/base.rb:52:in `block in perform'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/delivery_methods/base.rb:51:in `perform'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:59:in `block in _perform_job'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/i18n-1.10.0/lib/i18n.rb:323:in `with_locale'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `instance_exec'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:58:in `_perform_job'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:20:in `_perform_job'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:46:in `perform_now'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:14:in `block in perform_now'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:25:in `block in instrument'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/notifications.rb:206:in `instrument'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:35:in `instrument'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/instrumentation.rb:14:in `perform_now'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:18:in `block in perform_now'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:37:in `tagged'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/tagged_logging.rb:99:in `tagged'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:25:in `tag_logger'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/logging.rb:18:in `perform_now'
/Users/.../ruby/gems/3.1.0/gems/activejob-7.0.2.4/lib/active_job/execution.rb:18:in `perform_now'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:122:in `block in run_delivery_method'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:107:in `run_delivery_method'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:93:in `block in run_delivery'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:92:in `each'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:92:in `run_delivery'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:59:in `block (2 levels) in deliver'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:58:in `each'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:58:in `block in deliver'
/Users/.../ruby/gems/3.1.0/gems/activesupport-7.0.2.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/.../ruby/gems/3.1.0/gems/noticed-1.5.9/lib/noticed/base.rb:57:in `deliver'

NoMethodError: undefined method `to_sym' for #<Business id: 2, user_id: 26, contact_name: "Norman Mills", company: "Roob-Cartwright", created_at: "2022-04-08 21:55:36.854830000 +0000", updated_at: "2022-06-26 16:32:26.504735000 +0000", bio: "Consequuntur dolor provident. Dicta repellat odio....", developer_notifications: "no", website: "helloworld.com", contact_role: "", invisible: true>
Did you mean?  to_s
from /Users/.../ruby/gems/3.1.0/gems/activemodel-7.0.2.4/lib/active_model/attribute_methods.rb:458:in `method_missing'
```
</details>

**Comment by robingram** [comment]
I think this is by design - I came across this issue because I need exactly this functionality. If the notification class has a method with the same name as what is set by the `:method` option then the result of calling that will be used as the name of the mailer method. This provides some flexibility for dynamically setting the name of the method to call on the mailer.

https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/email.rb#L36

What you _could_ do is make use of that to get around your problem (I haven't tested this), e.g.:

```ruby
module Businesses
  class InvisiblizeNotification < ApplicationNotification
    deliver_by :database
    deliver_by :email, mailer: "InvisiblizeMailer", method: :mailer_method

    param :business

    def business
      params[:business]
    end

    def mailer_method
      :business
    end
  end
end
```

Note that `mailer_method` needs to be public AFAICT.
