### ISSUE TITLE
NameError - undefined local variable or method `recipient' for multiple deliveries

### ISSUE THREAD

**Issue by snake117** [excid3/noticed#31]
I am trying to send notifications to all `users` who are following the `user` who just posted a `Guide`. I am using the gem `acts_as_favoritor` to track which users are following whom. I am using an updated copy of JumpStart Pro and using Sidekiq to handle background jobs.

Here is the notification model `new_guide.rb`:
```
class NewGuide < ApplicationNotification
  # Database delivery is already added in ApplicationNotification
  deliver_by :action_cable, format: :to_websocket, channel: "NotificationChannel"

  # Add required params
  param :guide

  # Define helper methods to make rendering easier.
  # `message` and `url` are used for rendering in the navbar

  def message
    t(".new_guide", user: params[:guide].user.username, guide: params[:guide].title)
  end

  def url
    # You can use any URL helpers here such as:
    # post_path(params[:post])
    guide_path(params[:guide])
  end

  # Include account_id to make sure notification only triggers if user is signed in to that account
  def to_websocket
    {
      account_id: record.account_id,
      html: ApplicationController.render(partial: "notifications/notification", locals: {notification: record})
    }
  end
end
```

This is the portion of code in my `guides_controller.rb`:
```
if @guide.save
      following_personal_accounts = @guide.user.favoritors(scope: :user_follow).map(&:personal_account)
      notification = NewGuide.with(guide: @guide)
      notification.deliver_later(@guide.user.favoritors(scope: :user_follow))
      redirect_to @guide, notice: "Guide was successfully created."
 else
      render :new
end
```

Here is the error in the console:
```
Favorite Load (0.2ms)  SELECT "favorites".* FROM "favorites" WHERE "favorites"."favoritable_id" = $1 AND "favorites"."favoritable_type" = $2 AND "favorites"."blocked" = $3 AND "favorites"."scope" = $4  [["favoritable_id", 5], ["favoritable_type", "User"], ["blocked", false], ["scope", "user_follow"]]
22:29:43 web.1     |   ↳ app/controllers/guides_controller.rb:50:in `create'
22:29:43 web.1     |   User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 7]]
22:29:43 web.1     |   ↳ app/controllers/guides_controller.rb:50:in `create'
22:29:43 web.1     |   Account Load (0.2ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."owner_id" = $1 AND "accounts"."personal" = $2 LIMIT $3  [["owner_id", 7], ["personal", true], ["LIMIT", 1]]
22:29:43 web.1     |   ↳ app/controllers/guides_controller.rb:50:in `map'
22:29:43 web.1     |   CACHE Favorite Load (0.0ms)  SELECT "favorites".* FROM "favorites" WHERE "favorites"."favoritable_id" = $1 AND "favorites"."favoritable_type" = $2 AND "favorites"."blocked" = $3 AND "favorites"."scope" = $4  [["favoritable_id", 5], ["favoritable_type", "User"], ["blocked", false], ["scope", "user_follow"]]
22:29:43 web.1     |   ↳ app/controllers/guides_controller.rb:52:in `create'
22:29:43 web.1     |   CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 7]]
22:29:43 web.1     |   ↳ app/controllers/guides_controller.rb:52:in `create'
22:29:43 web.1     | [ActiveJob] [Noticed::DeliveryMethods::Database] [1a803188-b873-4cba-8208-ae49eded519a] Performing Noticed::DeliveryMethods::Database (Job ID: 1a803188-b873-4cba-8208-ae49eded519a) from Sidekiq(default) enqueued at  with arguments: {:notification_class=>"NewGuide", :options=>{:format=>:to_database}, :params=>{:guide=>#<GlobalID:0x00007ffcdd456988 @uri=#<URI::GID gid://caliber-revised/Guide/100>>}, :recipient=>#<GlobalID:0x00007ffcdd455fb0 @uri=#<URI::GID gid://caliber-revised/User/7>>, :record=>nil}
22:29:43 web.1     | [ActiveJob] [Noticed::DeliveryMethods::Database] [1a803188-b873-4cba-8208-ae49eded519a] Error performing Noticed::DeliveryMethods::Database (Job ID: 1a803188-b873-4cba-8208-ae49eded519a) from Sidekiq(default) in 13.0ms: NameError (undefined local variable or method `recipient' for #<NewGuide:0x00007ffcdeba5d50>):
22:29:43 web.1     | /Users/admin/Dropbox/Caliber/Revised/caliber_revised/app/notifications/application_notification.rb:10:in `to_database'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/delivery_methods/database.rb:17:in `attributes'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/delivery_methods/database.rb:6:in `deliver'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/delivery_methods/base.rb:18:in `block in perform'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/delivery_methods/base.rb:17:in `perform'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:40:in `block in perform_now'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/i18n-1.8.3/lib/i18n.rb:308:in `with_locale'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:25:in `block (4 levels) in <module:Logging>'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:24:in `block (3 levels) in <module:Logging>'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `block in tag_logger'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:45:in `tag_logger'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/logging.rb:21:in `block (2 levels) in <module:Logging>'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:39:in `perform_now'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activejob-6.0.3.2/lib/active_job/execution.rb:18:in `perform_now'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:96:in `block in run_delivery_method'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:94:in `run_delivery_method'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:73:in `run_delivery'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:55:in `block (2 levels) in deliver_later'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:54:in `each'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:54:in `block in deliver_later'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/noticed-1.2.2/lib/noticed/base.rb:53:in `deliver_later'
22:29:43 web.1     | /Users/admin/Dropbox/Caliber/Revised/caliber_revised/app/controllers/guides_controller.rb:52:in `create'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:195:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/searchkick-4.4.1/lib/searchkick/logging.rb:212:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionview-6.0.3.2/lib/action_view/rendering.rb:39:in `process'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:49:in `block in serve'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `each'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:834:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/cookies.rb:648:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:567:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_errors-2.7.1/lib/better_errors/middleware.rb:84:in `protected_app_call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_errors-2.7.1/lib/better_errors/middleware.rb:79:in `better_errors_call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/better_errors-2.7.1/lib/better_errors/middleware.rb:57:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:23:in `_call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:14:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/web-console-4.0.4/lib/web_console/middleware.rb:132:in `call_app'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/web-console-4.0.4/lib/web_console/middleware.rb:28:in `block in call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/web-console-4.0.4/lib/web_console/middleware.rb:17:in `catch'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/web-console-4.0.4/lib/web_console/middleware.rb:17:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/turbolinks_render-0.9.20/lib/turbolinks_render/middleware.rb:81:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:37:in `call_app'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `block in call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/static.rb:126:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/honeybadger-4.7.0/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/honeybadger-4.7.0/lib/honeybadger/agent.rb:401:in `with_rack_env'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/honeybadger-4.7.0/lib/honeybadger/rack/error_notifier.rb:30:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/honeybadger-4.7.0/lib/honeybadger/rack/user_feedback.rb:31:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/honeybadger-4.7.0/lib/honeybadger/rack/user_informer.rb:21:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/webpacker-5.1.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
22:29:43 web.1     | /Users/admin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
22:29:43 web.1     | Completed 500 Internal Server Error in 438ms (Searchkick: 11.4ms | ActiveRecord: 32.4ms | Allocations: 154962)
22:29:43 web.1     |
22:29:43 web.1     |
22:29:43 web.1     |
22:29:43 web.1     | NameError - undefined local variable or method `recipient' for #<NewGuide:0x00007ffcdeba5d50>:
22:29:43 web.1     |   app/notifications/application_notification.rb:10:in `to_database'
22:29:43 web.1     |   app/controllers/guides_controller.rb:52:in `create'
22:29:43 web.1     |
```
I feel like I'm missing something obvious here, but I just can't seem to figure it out. Even if I replace `notification.deliver_later(@guide.user.favoritors(scope: :user_follow))` with something like `notification.deliver_later(User.all)` I still get the same error.

Thanks in advance!

**Comment by excid3** [comment]
Looks like it couldn't access the `recipient` in your database format method.

What version of the Gem are you using? I believe I did see this before and we fixed this recently.

**Comment by snake117** [comment]
🤦‍♂️  Wow, yes that was the problem. I thought by updating the Jumpstart Pro template and running `bundle install` that `noticed` would be updated as well. Turns out I still had version `1.2.2` while the most updated version is `1.2.10`.

After running a simple `bundle update` everything now seems to work. I knew it had to be something obvious! 😝

Thanks for the help!

**Comment by excid3** [comment]
I'm glad it was that simple! 😜 I was worried I'd missed something important!
