### ISSUE TITLE
[BUG] FCM Delivery Method errors when config[:json] is a method

### ISSUE THREAD

**Issue by phil-6** [excid3/noticed#378]
### Describe the Bug:
at `/lib/noticed/delivery_methods/fcm.rb:17` 
the line
``` ruby
notification.instance_exec(device_token, &config[:json]))
```
in the `send_notification` method

Throws ` NoMethodError (undefined method 'android_format' for an instance of String):`

when `fcm.config.json = :android_format`

and `android_format` is a method that takes `device_token` as an argument and returns JSON

### To Reproduce:

Configure FCM Delivery Method
``` ruby
deliver_by :fcm do |config|
  config.credentials = Rails.root.join("config/certs/fcm.json")
  config.device_tokens = [ "eUlu_npTtR565sEADHeGXV:APA91bGgm2rssXgBdhjt9DDTZJShjnr_8OpxUB29zQQ4CvFCAl1exk9gYXluBJvj6q7EdMbO72A5E-N_LCHiIAGOOTiHqNo-iEwlckvEl2yfurbLCwRg0w84GqOf19pHgwaGd_1nZLF4" ]
  config.json = :android_format
end

def android_format(device_token)
  {
    token: device_token,
    notification: {
      title: "Test Title",
      body: "Test body"
    }
  }
end
```
Trigger a notification. 

### Expected Behavior

Notification to send correctly. 

### Actual Behavior

``` bash
2024-01-23T11:25:31.341Z pid=232233 tid=5im9 class=Noticed::DeliveryMethods::Fcm jid=26dbb4c80f7adef7db91de3c ERROR: Error performing Noticed::DeliveryMethods::Fcm (Job ID: 27faecc0-1464-42c0-b6f1-4888451ae0cd) from Sidekiq(default) in 332625.98ms: NoMethodError (undefined method `android_format' for an instance of String):
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_methods/fcm.rb:18:in `instance_exec'
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_methods/fcm.rb:18:in `send_notification'
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_methods/fcm.rb:10:in `block in deliver'
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_methods/fcm.rb:9:in `each'
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_methods/fcm.rb:9:in `deliver'
/home/phil/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.0.3/lib/noticed/delivery_method.rb:21:in `perform'
```

### Environment:
- Noticed gem version: 2.0.3
- Ruby version: 3.3.0
- Rails version: 7.1.3
- Operating System: Ubuntu 22.04

### Possible Fix:

Copy pattern from ios.md and implement a `format_notification` method.

Note: I'm not really a fan of the nested conditionals here

``` ruby
def format_notification(device_token)
  if (method = config[:json])
    if method.is_a?(Symbol) && event.respond_to?(method)
      event.send(method, device_token)
    else
      notification.instance_exec(device_token, &method)
    end
  else
    raise ArgumentError, "No json for fcm delivery. Add the 'json' option in 'deliver_by :fcm'."
  end
end
```
send notification method would then become

``` ruby
def send_notification(device_token)
  post_request("https://fcm.googleapis.com/v1/projects/#{credentials[:project_id]}/messages:send",
    headers: {authorization: "Bearer #{access_token}"},
    json: format_notification(device_token))
rescue Noticed::ResponseUnsuccessful => exception
  if exception.response.code == "404" && config[:invalid_token]
    notification.instance_exec(device_token, &config[:invalid_token])
  else
    raise
  end
end
```

This should mean that existing behaviour is not modified but adds the enhancement that `config[:json]` can be a symbol representation of a method.

Happy to put this up for PR if you're happy with the nested conditional.

### Checklist:

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by phil-6** [comment]
While trying to validate my possible fix, I think I've found a larger bug with the FCM Delivery method.

Using the example code, the FCM api responds with a 400.

example json payload:

``` ruby
config.json = ->(device_token) {
  {
    token: device_token,
    notification: {
      title: "Test Title",
      body: "Test body"
    }
  }
}
```

FCM Response
``` JSON
{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"token\": Cannot find field. Invalid JSON payload received. Unknown name \"notification\": Cannot find field.Invalid JSON payload received. Unknown name \"data\": Cannot find field.Invalid JSON payload received. Unknown name \"android\": Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"token\": Cannot find field."
          }, {
            "description": "Invalid JSON payload received. Unknown name \"notification\": Cannot find field."
          }
        ]
      }
    ]
  }
}
```
