### ISSUE TITLE
[BUG] Getting an undefined method gsub error when trying to use the twilio_messaging delivery method upon upgrade to V2

### ISSUE THREAD

**Issue by ykamin-booth** [excid3/noticed#396]
Upon upgrading to V2, I am having issues delivering notifications via Twilio. This is happening whether I move the delivery method to a block or keep it the way it was. 

Here it is as a block:

```
deliver_by :twilio_messaging do |config|
    config.json = ->{
      {
        From: "+12345678901",
        To: "+19876543210",
        Body: "this is a test"
      }
    }
  
    config.credentials = {
      phone_number: ENV.fetch("TWILIO_SENDING_PHONE_NUMBER"),
      account_sid: ENV.fetch("TWILIO_ACCOUNT_SID"),
      auth_token: ENV.fetch("TWILIO_AUTH_TOKEN")
    }
```

Based on the error below, this seems to have something to do with the way the json request to Twilio is uri encoded. The notification is getting created just fine in the database as well as being delivered correctly via ActionCable.

```
undefined method `gsub' for :From:Symbol
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:365:in `quote_string'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:321:in `block in encode_multipart_form_data'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:320:in `each'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:320:in `encode_multipart_form_data'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:303:in `send_request_with_body_data'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http/generic_request.rb:204:in `exec'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2335:in `block in transport_request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2333:in `catch'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2333:in `transport_request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2306:in `request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2299:in `block in request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:1570:in `start'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/net-http-0.4.1/lib/net/http.rb:2297:in `request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/noticed-2.1.2/lib/noticed/api_client.rb:36:in `post_request'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/noticed-2.1.2/lib/noticed/delivery_methods/twilio_messaging.rb:5:in `deliver'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/noticed-2.1.2/lib/noticed/delivery_method.rb:32:in `block in perform'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/noticed-2.1.2/lib/noticed/delivery_method.rb:31:in `perform'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/execution.rb:69:in `block in _perform_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/rails/active_job.rb:22:in `block in perform'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-ruby-6.2.2/lib/airbrake-ruby/benchmark.rb:13:in `measure'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/rails/active_job.rb:21:in `perform'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/rails/active_job.rb:45:in `block (2 levels) in <module:ActiveJob>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:141:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/execution.rb:68:in `_perform_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/instrumentation.rb:32:in `_perform_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/execution.rb:52:in `perform_now'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/instrumentation.rb:26:in `block in perform_now'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activerecord-7.1.3/lib/active_record/railties/job_runtime.rb:13:in `block in instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/instrumentation.rb:40:in `block in instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/notifications.rb:206:in `block in instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/notifications.rb:206:in `instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/instrumentation.rb:39:in `instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activerecord-7.1.3/lib/active_record/railties/job_runtime.rb:11:in `instrument'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/instrumentation.rb:26:in `perform_now'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/logging.rb:18:in `block in perform_now'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/tagged_logging.rb:135:in `block in tagged'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/tagged_logging.rb:39:in `tagged'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/tagged_logging.rb:135:in `tagged'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/broadcast_logger.rb:240:in `method_missing'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/logging.rb:25:in `tag_logger'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/logging.rb:18:in `perform_now'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/execution.rb:30:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/railtie.rb:67:in `block (4 levels) in <class:Railtie>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/reloader.rb:77:in `block in wrap'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/execution_wrapper.rb:92:in `wrap'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/reloader.rb:74:in `wrap'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/railtie.rb:66:in `block (3 levels) in <class:Railtie>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `instance_exec'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activesupport-7.1.3/lib/active_support/callbacks.rb:141:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/execution.rb:28:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/activejob-7.1.3/lib/active_job/queue_adapters/delayed_job_adapter.rb:47:in `perform'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/delayed_job.rb:12:in `block (3 levels) in <class:Airbrake>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-ruby-6.2.2/lib/airbrake-ruby/benchmark.rb:13:in `measure'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/delayed_job.rb:10:in `block (2 levels) in <class:Airbrake>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/backend/base.rb:78:in `invoke_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block (2 levels) in run'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/timeout-0.4.1/lib/timeout.rb:186:in `block in timeout'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/timeout-0.4.1/lib/timeout.rb:193:in `timeout'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:231:in `block in run'
/home/ubuntu/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:230:in `run'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `block in reserve_and_run_one_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:313:in `reserve_and_run_one_job'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:214:in `block in work_off'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `times'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:213:in `work_off'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:176:in `block (4 levels) in start'
/home/ubuntu/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/benchmark.rb:311:in `realtime'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:175:in `block (3 levels) in start'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:174:in `block (2 levels) in start'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `loop'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:173:in `block in start'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:79:in `block in add'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:66:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/worker.rb:172:in `start'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/delayed_job-4.1.11/lib/delayed/tasks.rb:9:in `block (2 levels) in <main>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:281:in `block in execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:281:in `each'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:281:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/airbrake-13.0.4/lib/airbrake/rake.rb:17:in `execute'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:199:in `synchronize'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/task.rb:188:in `invoke'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:182:in `invoke_task'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:138:in `each'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:138:in `block in top_level'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:147:in `run_with_threads'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:132:in `top_level'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:83:in `block in run'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
/home/ubuntu/.rvm/gems/ruby-3.2.1/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/bin/rake:25:in `load'
/home/ubuntu/.rvm/gems/ruby-3.2.1/bin/rake:25:in `<main>'
/home/ubuntu/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
/home/ubuntu/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

**Comment by excid3** [comment]
Hmm, I guess since our tests stub the request, it may not have caught this. https://github.com/excid3/noticed/blob/main/test/delivery_methods/twilio_messaging_test.rb#L11

**Comment by excid3** [comment]
Looks like net/http prefers these to be String keys so you can adjust that:

```ruby
deliver_by :twilio_messaging do |config|
    config.json = ->{
      {
        "From" => "+12345678901",
        "To" => "+19876543210",
        "Body" => "this is a test"
      }
    }
```

I will also add a `stringify_keys` to the Twilio Messaging delivery method to account for that so you can use symbols or keys.
