### ISSUE TITLE
[BUG] Noticed seems incompatible with MS SQL server (undefined method `has_key?' for an instance of String)

### ISSUE THREAD

**Issue by erlingur** [excid3/noticed#450]
## Bug Report

**Describe the Bug:**
When using Noticed with the MS SQL server adapter, it seems that the params get serialised as a string and Noticed isn't expecting that. This has something to do with ActiveJob it seems, but I'm not 100% sure. When I try to deliver a notification I get the error:

```
(irb):1:in `<main>': undefined method `has_key?' for an instance of String (NoMethodError)
        raise ValidationError, "Param `#{param_name}` is required for #{self.class.name}." unless params.has_key?(param_name)
```

**To Reproduce:**

1. Set up a fresh Rails 7.1 application, with the `tiny_tds` and `activerecord-sqlserver-adapter` gems (and noticed of course).
2. Generate a notifier
3. Try to deliver the notifier like so: `GenericNotifier.with(title: "Hello", message: "World").deliver(User.all)`

Repo that demonstrates the problem: https://github.com/erlingur/noticed-bug

You will need to launch a MS SQL container with Docker like so:

```
sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=sapassword" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest
```

If you have an issue installing `tiny_tds` you might have to install it like so:

`gem install tiny_tds -v '2.1.5' -- --with-freetds-include=/opt/homebrew/include --with-freetds-lib=/opt/homebrew/lib`

(This is what I have to do in my setup at least)

**Expected Behavior:**
I expect the notification to be delivered to all users

**Actual Behavior:**
I get an error:

```
(irb):1:in `<main>': undefined method `has_key?' for an instance of String (NoMethodError)
        raise ValidationError, "Param `#{param_name}` is required for #{self.class.name}." unless params.has_key?(param_name)
```

**Environment:**
- Noticed gem version: 2.3.1
- Ruby version: 3.3.1
- Rails version: 7.1.3
- Operating System: macOS Sonoma 14.5

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
We only test against Postgres, MySQL, and SQLite. Looks like you have a text column for `params` instead of `json`?

**Comment by erlingur** [comment]
Yeah, internally the `activerecord-sqlserver-adapter` will set a `json` column as `nvarchar(MAX)`.

I can actually "fix" this by creating a notifier like this:

```ruby
class GenericNotifier < Noticed::Event
  attribute :params, ActiveRecord::Type::SQLServer::Json.new
  required_params "title", "message"
end
```

**Comment by erlingur** [comment]
I am also not sure what's best to do here. I fixed this by defining my ApplicationNotifier like so:

```ruby
class ApplicationNotifier < Noticed::Event
  attribute :params, ActiveRecord::Type::SQLServer::Json.new

  def self.required_params(*args)
    super(*args.map(&:to_s))
  end
end
```

That way I can still define my notifiers like normal:

```ruby
class GenericNotifier < ApplicationNotifier
  required_params :title, :message
end
```

Maybe just a note in the docs is enough for this? I can live with this solution for my project at least.

**Comment by excid3** [comment]
That didn't work. Guess I'll just leave it alone. 😜

```
ActiveJob::SerializationError: Unsupported argument type: ActiveRecord::Type::Json
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activejob-7.1.3/lib/active_job/serializers.rb:34:in `serialize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activejob-7.1.3/lib/active_job/arguments.rb:114:in `serialize_argument'
    lib/noticed/coder.rb:14:in `dump'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/type/serialized.rb:29:in `serialize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/type/helpers/mutable.rb:8:in `cast'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/attribute.rb:199:in `type_cast'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/attribute.rb:43:in `value'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/attribute_set.rb:51:in `fetch_value'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/transactions.rb:421:in `block in restore_transaction_record_state'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/attribute_set.rb:98:in `transform_values'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activemodel-7.1.3/lib/active_model/attribute_set.rb:98:in `map'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/transactions.rb:420:in `restore_transaction_record_state'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/transactions.rb:345:in `rolledback!'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:200:in `block in rollback_records'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:263:in `run_action_on_records'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:199:in `rollback_records'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:527:in `block in rollback_transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:520:in `rollback_transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:539:in `rescue in block in within_new_transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:538:in `block in within_new_transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activesupport-7.1.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/transactions.rb:212:in `transaction'
    /Users/chris/.asdf/installs/ruby/3.3.1/lib/ruby/gems/3.3.0/gems/activerecord-7.1.3/lib/active_record/transactions.rb:301:in `transaction'
    app/models/concerns/noticed/deliverable.rb:97:in `deliver'
    app/models/concerns/noticed/deliverable.rb:84:in `deliver'
    test/delivery_method_test.rb:34:in `block in <class:DeliveryMethodTest>'
```

**Comment by erlingur** [comment]
Was that by changing the `default`? I noticed you only changed the default value and not the type of the attribute.

My change is making the type of the params attribute JSON

**Comment by excid3** [comment]
Oh thanks! That's exactly what I did wrong haha

**Comment by excid3** [comment]
Try out #451. Setting the type seems to be the missing piece so Rails handles all that nicely.

**Comment by erlingur** [comment]
Can confirm it works great! 😃 Thanks for fixing this! 🚀

**Comment by excid3** [comment]
You're welcome and thanks for the help on this! I think this'll fix other databases and be more compatible all around. 👍
